title: Chipprogrammer
short_title: CP
url: "https://chipprogrammer.github.io"
baseurl: "/amp-test"
logo: "/static/img/chip.svg"


enableTags: true
tagarray: []

paginate: 4
paginate_path: "/blog/page:num/"
highlighter: rouge
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
